[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install', 'cd apps/web && npm install']

[phases.build]
cmds = ['cd apps/web && npm run build']

[start]
cmd = 'npx serve -s apps/web/dist -p $PORT'
