export const BOTOX_ZONES = [
  'Frente (líneas horizontales)',
  'Entre cejas (glabela)',
  'Patas de gallo (periocular)',
  'Párpado inferior',
  'Cejas (lifting)',
  'Nariz (bunny lines)',
  'Labio superior (código de barras)',
  'Comisuras bucales',
  'Mentón (piel de naranja)',
  'Cuello (bandas platismales)',
  'Escote',
  'Sudoración axilar (hiperhidrosis)',
  'Sudoración palmar',
  'Sudoración plantar',
  'Mandíbula (bruxismo / máseteres)',
  'Migraña (puntos occipitales)',
  'Trampoline chin',
  'Gummy smile',
  'Nefertiti lift (cuello y mandíbula)',
  'Otra zona',
] as const
